//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankAppV2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public string FName { get; set; }
        public string LName { get; set; }
        public System.DateTime BrthDay { get; set; }
        public string Passport { get; set; }
        public Nullable<decimal> Finance { get; set; }
        public int BankRating { get; set; }
        public string ClStatus { get; set; }
        public string Adress { get; set; }
        public string WorkPlace { get; set; }
        public int ActivLevel { get; set; }
        public System.TimeSpan FrstTrans { get; set; }
    }
}
