//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankAppV2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company : IAsyncEnumerable
    {
        public string CompName { get; set; }
        public System.DateTime CreateDay { get; set; }
        public string INN { get; set; }
        public Nullable<decimal> Finance { get; set; }
        public int BankRating { get; set; }
        public string ClStatus { get; set; }
        public string Adress { get; set; }
        public int ActivLevel { get; set; }
        public Nullable<System.TimeSpan> FirstTrans { get; set; }
    }
}
